create table wallet
(
    user_id varchar(200),
    type    varchar(100),
    balance numeric,
    id      bigint generated by default as identity,
    active  boolean default true
);

alter table wallet
    owner to wallet_user;

create table transaction
(
    status             varchar(100) not null,
    amount             numeric      not null,
    balance_after      numeric,
    created_at         timestamp    not null,
    updated_at         timestamp    not null,
    wallet_id          bigint,
    type               varchar(100),
    reason             varchar(100),
    id                 varchar(300),
    external_reference varchar(300),
    description        varchar(300),
    schedule_id        integer,
    retry_time         timestamp,
    retry_count        integer
);

alter table transaction
    owner to wallet_user;

create table ledger
(
    type               varchar(100) not null,
    amount             numeric      not null,
    balance_after      numeric,
    created_at         timestamp    not null,
    wallet_id          bigint,
    transaction_id     varchar(300) not null,
    reason             varchar(300),
    external_reference varchar(300)
);

alter table ledger
    owner to wallet_user;

create table scheduled_withdrawal
(
    id         varchar(200) not null
        primary key,
    status     varchar(100) not null,
    amount     numeric      not null,
    time       timestamp    not null,
    created_at timestamp    not null,
    updated_at timestamp    not null,
    wallet_id  bigint
);

alter table scheduled_withdrawal
    owner to wallet_user;

